#!/bin/bash

rm -rf .venv
python3 -m venv .venv
source ./.venv/bin/activate
pip3 install -r requirements.txt

echo "please activate the virtual environment with 'source ./.venv/bin/activate' before executing 'python3 nmap2mysql.py'"